/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'daviddecoding' at '8/24/16 8:09 PM' with Gradle 2.11
 *
 * @author daviddecoding, @date 8/24/16 8:09 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
